name: dev_audio_processing

services:
  # Shared Redis instance
  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${VOLUME_DATA_PATH}/redis:/data

  # Audio Processing Service
  
  streamqueue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./streamqueue:/usr/src/app/streamqueue
      - ./shared_lib:/usr/src/app/shared_lib
    command: python -m streamqueue.main
    # command: tail -f /dev/null
    restart: unless-stopped
    ports:
      - "${TRANSCRIPTION_SERVICE_API_PORT}:${TRANSCRIPTION_SERVICE_API_PORT}"
    depends_on:
      - redis
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - API_HOST
      - TRANSCRIPTION_SERVICE_API_PORT
      - TRANSCRIPTION_SERVICE_API_TOKEN
      - AUDIO_CHUNK_DURATION_SEC
      - REDIS_PASSWORD
      - PYTHONPATH=/app/streamqueue:/app/shared_lib

      
  audio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${VOLUME_DATA_PATH}:/data/audio
      - ./app:/usr/src/app/app
      - ./shared_lib:/usr/src/app/shared_lib
    command: supervisord -c /usr/src/app/app/supervisord.conf
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    environment:
      - SERVICE_VERSION
      - REDIS_HOST
      - REDIS_PORT
      - AUDIO_CHUNK_DURATION_SEC
      - SEGMENT_SIZE_SEC
      - PROCESSING_THREADS
      - CHECK_AND_PROCESS_CONNECTIONS_INTERVAL_SEC
      - SPEAKER_DELAY_SEC
      - WHISPER_SERVICE_URL
      - WHISPER_PORT
      - WHISPER_API_TOKEN
      - REDIS_PASSWORD
      - TRANSCRIBER_STEP_SEC
      - MAX_AUDIO_LENGTH_SEC
      - ENGINE_API_PORT
      - ENGINE_API_URL
      - ENGINE_API_TOKEN
      - PYTHONPATH=/usr/src/app

networks:
  default:
    driver: bridge
