name: dev_audio_processing

services:
  # Shared Redis instance
  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${VOLUME_DATA_PATH}/redis:/data

  # Audio Processing Service
  
  streamqueue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./streamqueue:/usr/src/app/streamqueue
   # command: python streamqueue/main.py
    command: tail -f /dev/null
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - redis
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - API_HOST
      - API_PORT
      - API_TOKEN
      - AUDIO_CHUNK_DURATION_SEC
      - REDIS_PASSWORD

  audio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${VOLUME_DATA_PATH}:/data/audio
      - ./app:/usr/src/app/app
    #command: python app/main.py
    command: tail -f /dev/null
    restart: unless-stopped

    depends_on:
      - redis
    environment:
      - SERVICE_VERSION
      - REDIS_HOST
      - REDIS_PORT
      - AUDIO_CHUNK_DURATION_SEC
      - SEGMENT_SIZE_SEC
      - PROCESSING_THREADS
      - CHECK_AND_PROCESS_CONNECTIONS_INTERVAL_SEC
      - SPEAKER_DELAY_SEC
      - WHISPER_SERVICE_URL
      - WHISPER_API_TOKEN
      - RAW_AUDIO_PATH
      - SEGMENTS_PATH
      - REDIS_PASSWORD

networks:
  default:
    driver: bridge
