[tool.isort]
profile = 'black'
multi_line_output = 3
include_trailing_comma = 'True'
force_grid_wrap = 5
ensure_newline_before_comments = 'True'
line_length = 120
atomic = 'True'

[tool.black]
exclude ='''
(
  /(
      \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
    | venv
  )/
)
'''
line-length = 120
