# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01.diarize.ipynb.

# %% auto 0
__all__ = ['get_redis']

# %% ../nbs/01.diarize.ipynb 9
import redis.asyncio as aioredis
async def get_redis():
    
    db = await aioredis.from_url(
            "redis://host.docker.internal:6380/0",decode_responses=True
        )

    await db.ping()

    return db
